### ISSUE TITLE
Unable to Bind Value to Command.Input

### ISSUE THREAD

**Issue by ylor** [huntabyte/shadcn-svelte#459]
### Current Behavior

Binding a value to Command.Input causes 500 internal error

### Expected Behavior

To be able to bind a value to Command.Input to track state without crashing

### Steps To Reproduce

```
<script lang="ts">
	import * as Command from '$lib/components/ui/command';
	let str = '';
</script>

<form>
	<Command.Root>
		<Command.Input bind:value={str} placeholder="Type a command or search..." />
		<Command.List>
			<Command.Empty>No results found.</Command.Empty>
			<Command.Group heading="Suggestions">
				<Command.Item>Calendar</Command.Item>
				<Command.Item>Search Emoji</Command.Item>
				<Command.Item>Calculator</Command.Item>
			</Command.Group>
		</Command.List>
	</Command.Root>
</form>

{#if str.length > 0}
	asdf
{/if}
```

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://stackblitz.com/edit/github-t5awfc?file=src%2Froutes%2F%2Bpage.svelte

### More Information

Thank you very much for your work and time on this issue. It's much appreciated!

**Comment by fredguth** [comment]
Try updating ... it was fixed yesterday.

**Comment by huntabyte** [comment]
As @fredguth mentioned, check the recent updates to the `Command.Input` and it will work as expected.

**Comment by ylor** [comment]
I see the commit you're talking about over at [9366e1b](https://github.com/huntabyte/shadcn-svelte/commit/9366e1b00d5fb532d341d4a43912884dcc26ab2c).

Just started a fresh Sveltekit project, updated all dependencies, and ran `npx shadcn-svelte@latest add command` and it's still crashing for me.

**Comment by ylor** [comment]
After manually copying `export let value: string = "";` to `lib/components/ui/command/command-input.svelte`, it's now working.

Looks like the CLI somehow isn't pulling the latest instance of the Command component?
